[package]
name = "node"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
structopt = "0.3.26"
tokio = { version = "1.28.0", features = ["full"] }
lib = { path = "../lib" }
